name: Python release

on:
  workflow_dispatch:
  push:
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          pip install --upgrade pip setuptools
          pipi install -U numpy
      - name: Install dependencies on ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install valgrind libgomp1 cmake swig -y
      - name: Install dependencies on macos
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install valgrind libgomp1 cmake swig -y
      - name: Update submodules
        run: |
          git submodule init
          git submodule update
      - name: Build on Python ${{ matrix.python-version }}
        run: |
          mkdir build
          pushd build
          cmake -DWITH_OPENMP=ON $casadi_build_flags -DWITH_PROFILING=ON -DWITH_DOC=ON -DWITH_EXAMPLES=ON -DWITH_COVERAGE=ON -DWITH_EXTRA_WARNINGS=ON -DWITH_PYTHON=ON -DWITH_JSON=ON -DWITH_BLASFEO=ON -DWITH_BUILD_BLASFEO=ON -DWITH_HPMPC=ON -DWITH_BUILD_HPMPC=ON ..
          make -j2
          sudo make -j2 install
          popd
          python -c "from casadi.tools import *;loadAllCompiledPlugins()"
          python -c "from casadi import *"
          pushd test && make unittests_py_valgrind && popd
