name: Python release

on:
  workflow_dispatch:
  push:
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install -U numpy lxml
      - name: Install dependencies on ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libgomp1 cmake swig gcc graphviz texlive-science texlive-latex-base texlive-latex-recommended texlive-latex-extra -y
      - name: Install dependencies on macos
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install libgomp1 cmake swig gcc
      - name: Update submodules
        run: |
          git submodule init
          git submodule update
      - name: Build on Python ${{ matrix.python-version }}
        run: |
          echo "TESTMODE=full-py3" >> $GITHUB_ENV
          echo "WITH_PYTHON3=ON" >> $GITHUB_ENV
          mkdir build
          pushd build
          cmake -DWITH_OPENMP=OFF -DWITH_EXTRA_WARNINGS=ON -DWITH_EXTRA_CHECKS=OFF -DWITH_SLICOT=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_PROFILING=ON -DWITH_DOC=ON -DWITH_EXAMPLES=ON -DWITH_EXTRA_WARNINGS=ON -DWITH_PYTHON=ON -DWITH_PYTHON3=ON -DWITH_JSON=ON ..
          make -j2
          sudo make -j2 install
          popd
          python -c "from casadi.tools import *;loadAllCompiledPlugins()"
          python -c "from casadi import *"
          pushd test && make unittests_py && popd
